print("Hello world!!")
print("What is your name")
my_name = input()
print("Nice meeting you," + my_name)
print("What is your favourite food?")
favourite_food = input()
print("What is your best colour?")
best_colour = input()
print("wow, so your best food is " + favourite_food + " and your best colour is " + best_colour )